name: Build Release

on:
  push:
    tags:
      - "v*"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/golang@master
        with:
          go-version: '1.19'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      - name: Build Binaries
        run: make versioned-binaries
        env:
          MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
      - name: Uploading Binaries
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.FLOW_HOSTING_PROD_SA }}
          path: ./cmd/flow/
          glob: 'flow-*'
          destination: flow-cli/
          parent: false
      - name: Update Version
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.FLOW_HOSTING_PROD_SA }}
          path: ./
          glob: 'version.txt'
          destination: flow-cli/
